---
- name: Run whoami without become.
  command: whoami
  changed_when: false
  become: false
  delegate_to: localhost
  register: whoami

- name: Set a fact with the user name.
  set_fact:
    login_user: "{{ whoami.stdout }}"

- name: Verificando se existe uma chave ssh no home do usuário
  stat:
    path: /home/{{ login_user }}/.ssh/id_rsa
  delegate_to: localhost
  register: ssh_key_exist

- name: Gerando chave ssh no home do usuário ansible
  shell: >
    yes y | ssh-keygen -t rsa -q -N "" -f /home/{{ login_user }}/.ssh/id_rsa
  delegate_to: localhost
  when: (not ssh_key_exist.stat.exists)

- name: Add a new user named ansible
  user:
    name: ansible
    shell: /bin/bash

- name: Add ansible user to the sudoers
  copy:
    dest: "/etc/sudoers.d/ansible"
    content: "ansible  ALL=(ALL)  NOPASSWD: ALL"

- name: Deploy SSH Key
  authorized_key: 
    user: ansible
    key: "{{ lookup('file', '/home/{{ login_user }}/.ssh/id_rsa.pub') }}"
    state: present