---
- name: Get list of defined networks
  virt_net:
    command: list_nets
  register: netlist

- name: Show net list 
  debug:
    var:
      netlist

- name: Deactivate if exists
  virt_net:
    command: destroy
    name: "{{ item.name }}"
  when: item.name in netlist.list_nets
  with_items: "{{ networks }}"
  ignore_errors: yes

- name: Undefine if exists
  virt_net:
    command: undefine
    name: "{{ item.name }}"
  when: item.name in netlist.list_nets
  with_items: "{{ networks }}"