networks:

  # network nat
  - name: test
    forward:
      mode: nat
      port:
        start: 1025
        end: 65535
    bridge:
      name: virbr3
      stp: on
      delay: 0
    hwaddr: 52:54:00:f7:34:54
    domainname: internal
    ipaddr: 192.168.126.2
    netmask: 255.255.255.0
    dhcp_range:
      start: 192.168.126.2
      end: 192.168.126.253

  # private net
  - name: test2
    bridge:
      name: virbr2
      stp: on
      delay: 0
    hwaddr: 52:54:00:f7:34:57
    domainname: internal
    ipaddr: 192.168.127.1
    netmask: 255.255.255.0
    dhcp_range:
      start: 192.168.127.2
      end: 192.168.127.254