---
- name: Modifica configuração do SSH 
  template: 
    src: "templates/sshd_config.j2"
    dest: "/etc/ssh/sshd_config"

- name: restart ssh
  service: 
    name: sshd
    state: restarted
    enabled: yes